name: Trigger auto deployment for container-app-4kttq2iyhc5mk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-4kttq2iyhc5mk-AutoDeployTrigger-c9e142d2-6704-4aa5-8cd3-9649303b7030.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4KTTQ2IYHC5MK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4KTTQ2IYHC5MK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4KTTQ2IYHC5MK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP4KTTQ2IYHC5MK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4KTTQ2IYHC5MK_REGISTRY_PASSWORD }}
          containerAppName: container-app-4kttq2iyhc5mk
          resourceGroup: todonodejspgsqlgoogleauthb52a92ed
          imageToBuild: default/container-app-4kttq2iyhc5mk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


